Lifecycle:
    RestartOnAppFailure: true
Logging:
    LogLevel:
        Default: Information

Interlock:
    Enabled: true

GearUnlock:
    Enabled: true
    Delay: 50

Switch:
    Low4:
        Min: 1.0
        Max: 1.23
    High4:
        Min: 1.23
        Max: 1.52
    High2:
        Min: 1.52
        Max: 2.25
TCase:
    Low4:
        Min: 1.20
        Max: 1.70
    High4:
        Min: 3.20
        Max: 3.70
    High2:
        Min: 2.20
        Max: 2.70
