Lifecycle:
    RestartOnAppFailure: true
Logging:
    LogLevel:
        Default: Information

Interlock:
    Enabled: true

GearUnlock:
    Enabled: true
    Delay: 50

Switch:
    Low4:
        Min: 1.0
        Max: 1.23
    High4:
        Min: 1.23
        Max: 1.52
    High2:
        Min: 1.52
        Max: 2.25
TCase:
    Low4:
        Min: 1.36
        Max: 1.45
    High4:
        Min: 3.38
        Max: 3.56
    High2:
        Min: 2.41
        Max: 2.52
